default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: apartment_development

test:
  <<: *default
  database: apartment_test

production:
  <<: *default
  database: apartment
